/* Generated By:JJTree&JavaCC: Do not edit this line. AnimTimeParserConstants.java */
package com.kitfox.svg.animation.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnimTimeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int INTEGER = 8;
  /** RegularExpression Id. */
  int FLOAT = 9;
  /** RegularExpression Id. */
  int INDEFINITE = 10;
  /** RegularExpression Id. */
  int MOUSE_OVER = 11;
  /** RegularExpression Id. */
  int WHEN_NOT_ACTIVE = 12;
  /** RegularExpression Id. */
  int UNITS = 13;
  /** RegularExpression Id. */
  int IDENTIFIER = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<LETTER>",
    "<DIGIT>",
    "<INTEGER>",
    "<FLOAT>",
    "\"indefinite\"",
    "\"mouseover\"",
    "\"whenNotActive\"",
    "<UNITS>",
    "<IDENTIFIER>",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\":\"",
    "\".\"",
    "\"(\"",
    "\")\"",
  };

}
