/* Generated By:JavaCC: Do not edit this line. AnimTimeParserTreeConstants.java Version 5.0 */
package com.kitfox.svg.animation.parser;

public interface AnimTimeParserTreeConstants
{
  public int JJTEXPR = 0;
  public int JJTSUM = 1;
  public int JJTTERM = 2;
  public int JJTINDEFINITETIME = 3;
  public int JJTEVENTTIME = 4;
  public int JJTLITERALTIME = 5;
  public int JJTLOOKUPTIME = 6;
  public int JJTPARAMLIST = 7;
  public int JJTNUMBER = 8;
  public int JJTINTEGER = 9;


  public String[] jjtNodeName = {
    "Expr",
    "Sum",
    "Term",
    "IndefiniteTime",
    "EventTime",
    "LiteralTime",
    "LookupTime",
    "ParamList",
    "Number",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=f9b612888b81922f0418b890bad7527d (do not edit this line) */
