/* Generated By:JJTree: Do not edit this line. ASTEventTime.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.kitfox.svg.animation.parser;

public
class ASTEventTime extends SimpleNode {
  public ASTEventTime(int id) {
    super(id);
  }

  public ASTEventTime(AnimTimeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=87793ac7764e55d18e5a52ec210e51c2 (do not edit this line) */
