/* Generated By:JJTree: Do not edit this line. ASTIndefiniteTime.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.kitfox.svg.animation.parser;

public
class ASTIndefiniteTime extends SimpleNode {
  public ASTIndefiniteTime(int id) {
    super(id);
  }

  public ASTIndefiniteTime(AnimTimeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8e9adeaf8df3cf8e58c23a73542164e1 (do not edit this line) */
