/* Generated By:JJTree: Do not edit this line. ASTLiteralTime.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.kitfox.svg.animation.parser;

public
class ASTLiteralTime extends SimpleNode {
  public ASTLiteralTime(int id) {
    super(id);
  }

  public ASTLiteralTime(AnimTimeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e835e7b1897f635ba59b840fc50ca1a4 (do not edit this line) */
