/* Generated By:JJTree: Do not edit this line. ASTLookupTime.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.kitfox.svg.animation.parser;

public
class ASTLookupTime extends SimpleNode {
  public ASTLookupTime(int id) {
    super(id);
  }

  public ASTLookupTime(AnimTimeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=388e762dd7d67479f8f900bac51accbf (do not edit this line) */
