/* Generated By:JJTree: Do not edit this line. ASTSum.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.kitfox.svg.animation.parser;

public
class ASTSum extends SimpleNode {
  public ASTSum(int id) {
    super(id);
  }

  public ASTSum(AnimTimeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=219697ddc7811e985057c491fdca56a7 (do not edit this line) */
